name: dnq-dlc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - box2d-py=2.3.8
  - numpy=1.26
  - pyglet=1.5
  - shapely=1.8
  - pip:
      - gym==0.17.2
      - gymnasium>=0.29,<1.3
      - matplotlib>=3.7,<4
      - pandas>=2.0,<3
      - pillow>=10,<12
      - stable-baselines3>=2.3,<3
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch
